version: "3.9"

services:

  postgres:
    image: postgres:16

    environment:
      POSTGRES_DB: janitri_db
      POSTGRES_USER: janitri_user
      POSTGRES_PASSWORD: janitri123

    ports:
      - "5432:5432"

  backend:
    build: .

    ports:
      - "8000:8000"

    depends_on:
      - postgres

    env_file:
      - .env